### ISSUE TITLE
Hate to be that guy...

### ISSUE THREAD

**Issue by newswim** [developit/preact-in-es3#2]
But [here](https://github.com/developit/preact-in-es3/blob/master/index.js#L11) you're using `Object.create`, which was introduced in ES 5.1

I know! I know!! I'm horrible.

**Comment by developit** [comment]
haha good catch. Want to PR the fix? It's fine to just invoke the constructor, it doesn't really do much.

**Comment by newswim** [comment]
Sure!

**Comment by newswim** [comment]
Submitted #3, I was trying to make this a lot more difficult than it ended up being. Thanks for the opportunity :]

**Comment by developit** [comment]
Looks perfect! :)
